export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const ADD_BUN = "ADD_BUN";
export const DELETE_ITEM = "DELETE_ITEM";
export const REORDER_INGREDIENTS = "REORDER_INGREDIENTS"
export const SET_DEFAULT_VALUE_INGREDIENTS = "SET_DEFAULT_VALUE_INGREDIENTS"